name: testplugin
version: '${version}'
main: fr.gamordstrimer.testplugin.Main
api-version: '1.20'
commands:
  customitemsgive:
    description: Donne un les items customs du plugin au joueur
    usage: /givecustomitem <itemName> [amount]
    aliases:
      - cig
  customitemsrecipes:
    description: Affiche une interface permettant de connaitre les différents craft des items customs du serveur
    usage: /customitemsrecipes
    aliases:
      - cir
  resetcooldown:
    description: Permet de reset le cooldown lié à un joueur
    usage: /resetcooldown [Player]
  freeze:
    description: Permet de Gelé un joueur
    usage: /freeze [Player]
  staff:
    description: Permet d'activer le mode de modération
    usage: /staff
  vanish:
    description: Permet de devenir invisible au yeux des joueurs
    usage: /vanish